CREATE DATABASE HMS;
USE HMS;
CREATE TABLE DOCTOR(
   DID   INT              NOT NULL,
   DNAME VARCHAR (20)     NOT NULL,
   DAGE  INT              NOT NULL,
   DADDRESS  VARCHAR (50) ,
   DSALARY   INT,
   DEPID INT,
   HID INT,
   PRIMARY KEY (DID)
);

CREATE TABLE HOSPITAL(
   HID   INT              NOT NULL,
   HNAME VARCHAR (20)     NOT NULL,
   HADDRESS  VARCHAR (50) ,
   PRIMARY KEY (HID)
);
CREATE TABLE PATIENT(
   PID   INT              NOT NULL,
   PNAME VARCHAR (20)     NOT NULL,
   PAGE  INT              NOT NULL,
   PGENDER VARCHAR(20),
   PADDRESS  VARCHAR (50) ,
   DID   INT,
   DOA DATE,
   DOD DATE,
   PRIMARY KEY (PID)
);

CREATE TABLE DEPARTMENT(
   DEPID   INT              NOT NULL,
   DEPNAME VARCHAR (20)     NOT NULL,
   PRIMARY KEY (DEPID)
);
